CREATE TABLE public.password_resets (
    id BIGSERIAL NOT NULL,
    email TEXT NOT NULL,
    otp VARCHAR(6) NOT NULL,
    expiry TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used BOOLEAN NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_resets_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
